# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# create_streamlines.py
# Created on: 2020-01-17 19:30:16.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: create_streamlines <StreamLines> <yose_valley_tiles_rst05> 
# Description: 
# Creates a hydrographic network from a DEM based on a minimum area threshold
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
StreamLines = arcpy.GetParameterAsText(0)
if StreamLines == '#' or not StreamLines:
    StreamLines = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\results.gdb\\Stream_Lines" # provide a default value if unspecified

yose_valley_tiles_rst05 = arcpy.GetParameterAsText(1)
if yose_valley_tiles_rst05 == '#' or not yose_valley_tiles_rst05:
    yose_valley_tiles_rst05 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\results.gdb\\yose_valley_tiles_rst05" # provide a default value if unspecified

# Local variables:
Fill_sample_rst1_tif = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Fill_yose_va1"
Extent = "262530.4112 4175140.0246 284913.2599 4184347.6064"
Cell_Size = "MAXOF"
Output_drop_raster = ""
Output_flow_direction_raster = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\FlowDir_Fill1"
Output_accumulation_raster = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\FlowAcc_Flow1"
Cells_SQL_Expression = "VALUE < 100"
HydroNetwork = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\SetNull_Flow1"
StreamLinks = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\StreamL_SetN1"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"

# Process: Fill
arcpy.gp.Fill_sa(yose_valley_tiles_rst05, Fill_sample_rst1_tif, "")

# Process: Flow Direction
tempEnvironment0 = arcpy.env.extent
arcpy.env.extent = Extent
tempEnvironment1 = arcpy.env.cellSize
arcpy.env.cellSize = Cell Size
arcpy.gp.FlowDirection_sa(Fill_sample_rst1_tif, Output_flow_direction_raster, "NORMAL", Output_drop_raster, "D8")
arcpy.env.extent = tempEnvironment0
arcpy.env.cellSize = tempEnvironment1

# Process: Flow Accumulation
arcpy.gp.FlowAccumulation_sa(Output_flow_direction_raster, Output_accumulation_raster, "", "FLOAT", "D8")

# Process: Set Null
arcpy.gp.SetNull_sa(Output_accumulation_raster, Output_accumulation_raster, HydroNetwork, Cells_SQL_Expression)

# Process: Stream Link
arcpy.gp.StreamLink_sa(HydroNetwork, Output_flow_direction_raster, StreamLinks)

# Process: Stream to Feature
arcpy.gp.StreamToFeature_sa(StreamLinks, Output_flow_direction_raster, StreamLines, "NO_SIMPLIFY")

