# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# create_gdb_and_import_park_data.py
# Created on: 2020-01-17 19:29:11.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: create_gdb_and_import_park_data <data> <v_park_gdb_name> <park_data_gdb> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
data = arcpy.GetParameterAsText(0)
if data == '#' or not data:
    data = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data" # provide a default value if unspecified

v_park_gdb_name = arcpy.GetParameterAsText(1)
if v_park_gdb_name == '#' or not v_park_gdb_name:
    v_park_gdb_name = "park_data" # provide a default value if unspecified

park_data_gdb = arcpy.GetParameterAsText(2)
if park_data_gdb == '#' or not park_data_gdb:
    park_data_gdb = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\park_data.gdb" # provide a default value if unspecified

# Local variables:
Rivers = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yose_hydrology_dataset\\Hydrology.gdb\\Rivers"
Springs = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yose_hydrology_dataset\\Hydrology.gdb\\Springs"
Waterbodies = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yose_hydrology_dataset\\Hydrology.gdb\\Waterbodies"
Rock_Fall_Hazard_line_shp = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_RockFallHazardLine_shapefile\\Rock_Fall_Hazard_line.shp"
Trails = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Trails_geodatabase\\Trails.gdb\\All_trails\\Trails"
Wilderness_stock_routes = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Trails_geodatabase\\Trails.gdb\\All_trails\\Wilderness_stock_routes"
Winter_trails = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Trails_geodatabase\\Trails.gdb\\All_trails\\Winter_trails"
Trailheads = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Trails_geodatabase\\Trails.gdb\\All_trails\\Trailheads"
YOSE_CADBaseMap_20190905 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yosemite_CAD_BaseMap\\YOSE_CADBaseMap.gdb\\YOSE_CADBaseMap_20190905"
Yosemite_Climbing_Areas_shp = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yosemite_Climbing_Areas\\Yosemite_Climbing_Areas.shp"
YOSE_Parking_20190521 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Parking.gdb\\YOSE_Parking_20190521"
Yosemite_Roads = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Roads.gdb\\Yosemite_Roads"
yoseglg = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yosemite_Geology\\yose_geology.mdb\\yose\\yoseglg"
park_data_gdb__2_ = park_data_gdb

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\scratch.gdb"
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\scratch.gdb"

# Process: Create File GDB
arcpy.CreateFileGDB_management(data, v_park_gdb_name, "CURRENT")

# Process: Feature Class to Geodatabase (multiple) 
arcpy.FeatureClassToGeodatabase_conversion("'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yose_hydrology_dataset\\Hydrology.gdb\\Rivers';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yose_hydrology_dataset\\Hydrology.gdb\\Springs';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yose_hydrology_dataset\\Hydrology.gdb\\Waterbodies';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_RockFallHazardLine_shapefile\\Rock_Fall_Hazard_line.shp';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Trails_geodatabase\\Trails.gdb\\All_trails\\Trails';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Trails_geodatabase\\Trails.gdb\\All_trails\\Wilderness_stock_routes';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Trails_geodatabase\\Trails.gdb\\All_trails\\Winter_trails';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Trails_geodatabase\\Trails.gdb\\All_trails\\Trailheads';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yosemite_CAD_BaseMap\\YOSE_CADBaseMap.gdb\\YOSE_CADBaseMap_20190905';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yosemite_Climbing_Areas\\Yosemite_Climbing_Areas.shp';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Parking.gdb\\YOSE_Parking_20190521';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\YOSE_Roads.gdb\\Yosemite_Roads';'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\raw_data\\Yosemite_Geology\\yose_geology.mdb\\yose\\yoseglg'", park_data_gdb)

