# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# create_naip_mosaic.py
# Created on: 2020-01-17 19:29:45.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: create_naip_mosaic <v_aerial_mosaic_name> <data> <Yose_Aerial_Mosaic_Dataset> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy

# Script arguments
v_aerial_mosaic_name = arcpy.GetParameterAsText(0)
if v_aerial_mosaic_name == '#' or not v_aerial_mosaic_name:
    v_aerial_mosaic_name = "Yose_Aerial_Mosaic_Dataset" # provide a default value if unspecified

data = arcpy.GetParameterAsText(1)
if data == '#' or not data:
    data = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data" # provide a default value if unspecified

Yose_Aerial_Mosaic_Dataset = arcpy.GetParameterAsText(2)
if Yose_Aerial_Mosaic_Dataset == '#' or not Yose_Aerial_Mosaic_Dataset:
    Yose_Aerial_Mosaic_Dataset = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\AerialNAIPCollection.gdb\\Yose_Aerial_Mosaic_Dataset" # provide a default value if unspecified

# Local variables:
Aerial_NAIP_Collection = data
Yose_Aerial_Mosaic_Dataset__2_ = Yose_Aerial_Mosaic_Dataset
Yose_aerial = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\Yose_aerial"
Yose_Aerial_Mosaic_Dataset__3_ = Yose_Aerial_Mosaic_Dataset__2_

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"

# Process: Create File GDB
arcpy.CreateFileGDB_management(data, "AerialNAIPCollection", "CURRENT")

# Process: Create Mosaic Dataset
arcpy.CreateMosaicDataset_management(Aerial_NAIP_Collection, v_aerial_mosaic_name, "PROJCS['NAD_1983_UTM_Zone_11N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-117.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision", "", "", "NONE", "")

# Process: Add Rasters To Mosaic Dataset
arcpy.AddRastersToMosaicDataset_management(Yose_Aerial_Mosaic_Dataset, "Raster Dataset", "'D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\Yose_aerial'", "UPDATE_CELL_SIZES", "UPDATE_BOUNDARY", "NO_OVERVIEWS", "", "0", "1500", "PROJCS['NAD_1983_UTM_Zone_11N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-117.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5120900 -9998100 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision", "", "SUBFOLDERS", "ALLOW_DUPLICATES", "NO_PYRAMIDS", "NO_STATISTICS", "NO_THUMBNAILS", "", "NO_FORCE_SPATIAL_REFERENCE", "NO_STATISTICS", "")

# Process: Build Overviews
arcpy.BuildOverviews_management(Yose_Aerial_Mosaic_Dataset__2_, "", "DEFINE_MISSING_TILES", "GENERATE_OVERVIEWS", "GENERATE_MISSING_IMAGES", "REGENERATE_STALE_IMAGES")

