# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# hillshade.py
# Created on: 2020-01-17 19:30:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
yose_valley_tiles_rst05 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\results.gdb\\yose_valley_tiles_rst05"
yose_valley_rst05_hillshade = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\results.gdb\\yose_valley_rst05_hillshade"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"

# Process: Hillshade
arcpy.gp.HillShade_sa(yose_valley_tiles_rst05, yose_valley_rst05_hillshade, "315", "45", "NO_SHADOWS", "1")

