# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# iterate_and_clip_valley_data.py
# Created on: 2020-01-19 19:35:45.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: iterate_and_clip_valley_data <AOI> <park_data_gdb> 
# Description: 
# Clip the Yosemite Park Data by LIDAR maximum extent
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
AOI = arcpy.GetParameterAsText(0)

park_data_gdb = arcpy.GetParameterAsText(1)

# Local variables:
Name = "FeatureClass"
Feature_Class = "\\FeatureClass"
v_Name__clp = "%Name%_clp"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"

# Process: Iterate Feature Classes
tempEnvironment0 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
tempEnvironment1 = arcpy.env.workspace
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"
arcpy.IterateFeatureClasses_mb(park_data_gdb, "", "", "RECURSIVE")
arcpy.env.scratchWorkspace = tempEnvironment0
arcpy.env.workspace = tempEnvironment1

# Process: Clip
tempEnvironment0 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
tempEnvironment1 = arcpy.env.workspace
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"
arcpy.Clip_analysis(Feature_Class, AOI, v_Name__clp, "")
arcpy.env.scratchWorkspace = tempEnvironment0
arcpy.env.workspace = tempEnvironment1

