# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# iterate_and_clip_valley_data.py
# Created on: 2020-01-17 19:31:30.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: iterate_and_clip_valley_data <park_data_gdb> <AOI> 
# Description: 
# Clip the Yosemite Park Data by LIDAR maximum extent
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
park_data_gdb = arcpy.GetParameterAsText(0)
if park_data_gdb == '#' or not park_data_gdb:
    park_data_gdb = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\park_data.gdb" # provide a default value if unspecified

AOI = arcpy.GetParameterAsText(1)
if AOI == '#' or not AOI:
    AOI = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\helper_data.gdb\\AOI" # provide a default value if unspecified

# Local variables:
Name = "Rivers"
Featue_Class = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\park_data.gdb\\Rivers"
v_Name__clp = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\valley_data.gdb\\%Name%_clp"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\scratch.gdb"
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\scratch.gdb"

# Process: Iterate Feature Classes
tempEnvironment0 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\scratch.gdb"
tempEnvironment1 = arcpy.env.workspace
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\scratch.gdb"
arcpy.IterateFeatureClasses_mb(park_data_gdb, "", "", "RECURSIVE")
arcpy.env.scratchWorkspace = tempEnvironment0
arcpy.env.workspace = tempEnvironment1

# Process: Clip
tempEnvironment0 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = "C:\\Users\\suns\\Documents\\ArcGIS\\Default.gdb"
tempEnvironment1 = arcpy.env.workspace
arcpy.env.workspace = "C:\\Users\\suns\\Documents\\ArcGIS\\Default.gdb"
arcpy.Clip_analysis(Featue_Class, AOI, v_Name__clp, "")
arcpy.env.scratchWorkspace = tempEnvironment0
arcpy.env.workspace = tempEnvironment1

