# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# iterate_and_clip_valley_data.py
# Created on: 2020-01-19 18:50:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: iterate_and_clip_valley_data <park_data_gdb> <AOI> 
# Description: 
# Clip the Yosemite Park Data by LIDAR maximum extent
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
park_data_gdb = arcpy.GetParameterAsText(0)

AOI = arcpy.GetParameterAsText(1)

# Local variables:
Name = "FeatureClass"
Featue_Class = "\\FeatureClass"
v_Name__clp = "%Name%_clp"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"

# Process: Iterate Feature Classes
tempEnvironment0 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\scratch.gdb"
tempEnvironment1 = arcpy.env.workspace
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\scratch.gdb"
arcpy.IterateFeatureClasses_mb(park_data_gdb, "", "", "RECURSIVE")
arcpy.env.scratchWorkspace = tempEnvironment0
arcpy.env.workspace = tempEnvironment1

# Process: Clip
tempEnvironment0 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = "C:\\Users\\suns\\Documents\\ArcGIS\\Default.gdb"
tempEnvironment1 = arcpy.env.workspace
arcpy.env.workspace = "C:\\Users\\suns\\Documents\\ArcGIS\\Default.gdb"
arcpy.Clip_analysis(Featue_Class, AOI, v_Name__clp, "")
arcpy.env.scratchWorkspace = tempEnvironment0
arcpy.env.workspace = tempEnvironment1

