# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# junk.py
# Created on: 2020-01-17 19:32:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Best_Climbing_Criteria = "Best_Climbing_Criteria"
Input_true_raster_or_constant_value = "1"
Con_Best_Cli1 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Con_Best_Cli1"
RegionG_Con_1 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\RegionG_Con_1"
RasterT_RegionG1 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\RasterT_RegionG1"
RasterT_RegionG1_Dissolve = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\RasterT_RegionG1_Dissolve"
RasterT_RegionG1_Dissolve_Bu = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\RasterT_RegionG1_Dissolve_Bu"
RasterT_RegionG1_Dissolve_Bu1 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\RasterT_RegionG1_Dissolve_Bu1"
Possible_Climbing_Slopes = "Possible Climbing Slopes"
Reclass_Poss1 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Reclass_Poss1"
Possible_Climbing_Slopes__2_ = "Possible Climbing Slopes"
PossibleClimbingSlopesLowres_kmz = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\Online\\kmz\\PossibleClimbingSlopesLowres.kmz"
Possible_Climbing_Walls = "Possible Climbing Walls"
PossibleClimbingWallsLowres_kmz = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\Online\\kmz\\PossibleClimbingWallsLowres.kmz"
Best_Climbing_Walls = "Best Climbing Walls"
BestClimbingZonesHires_kmz = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\Online\\kmz\\BestClimbingZonesHires.kmz"
yose_valley_tiles_rst05 = "New Group Layer\\yose_valley_tiles_rst05"
yose_valley_elevation_low_kmz = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\Online\\kmz\\yose_valley_elevation_low.kmz"
yose_valley_rst05_hillshade__2_ = "New Group Layer\\yose_valley_rst05_hillshade"
yose_valley_hillshade_low_kmz = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\Online\\kmz\\yose_valley_hillshade_low.kmz"
Possible_Climbing_Areas_Class = "Possible_Climbing_Areas_Class"
PossibleClimbingSlopesLowres_kmz__3_ = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\Online\\kmz\\PossibleClimbingSlopesLowres.kmz"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"

# Process: Con
arcpy.gp.Con_sa(Best_Climbing_Criteria, Input_true_raster_or_constant_value, Con_Best_Cli1, "", "Value = 10")

# Process: Region Group
arcpy.gp.RegionGroup_sa(Con_Best_Cli1, RegionG_Con_1, "EIGHT", "WITHIN", "ADD_LINK", "")

# Process: Raster to Polygon
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolygon_conversion(RegionG_Con_1, RasterT_RegionG1, "NO_SIMPLIFY", "VALUE", "SINGLE_OUTER_PART", "")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

# Process: Dissolve
arcpy.Dissolve_management(RasterT_RegionG1, RasterT_RegionG1_Dissolve, "", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Buffer
arcpy.Buffer_analysis(RasterT_RegionG1_Dissolve, RasterT_RegionG1_Dissolve_Bu, "10 Meters", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Mean Center
arcpy.MeanCenter_stats(RasterT_RegionG1_Dissolve_Bu, RasterT_RegionG1_Dissolve_Bu1, "", "", "")

# Process: Reclassify
arcpy.gp.Reclassify_sa(Possible_Climbing_Slopes, "VALUE", "0.002473 10 1;10 20 2;20 30 3;30 40 4;40 50 5;50 60 6;60 70 7;70 80 8;80 90 9", Reclass_Poss1, "DATA")

# Process: Layer To KML
arcpy.LayerToKML_conversion(Possible_Climbing_Slopes__2_, PossibleClimbingSlopesLowres_kmz, "0", "NO_COMPOSITE", "DEFAULT", "10240", "300", "CLAMPED_TO_GROUND")

# Process: Layer To KML (2)
arcpy.LayerToKML_conversion(Possible_Climbing_Walls, PossibleClimbingWallsLowres_kmz, "0", "COMPOSITE", "DEFAULT", "10240", "300", "CLAMPED_TO_GROUND")

# Process: Layer To KML (3)
arcpy.LayerToKML_conversion(Best_Climbing_Walls, BestClimbingZonesHires_kmz, "0", "NO_COMPOSITE", "DEFAULT", "61440", "300", "CLAMPED_TO_GROUND")

# Process: Layer To KML (4)
arcpy.LayerToKML_conversion(yose_valley_tiles_rst05, yose_valley_elevation_low_kmz, "0", "NO_COMPOSITE", "DEFAULT", "30720", "300", "ABSOLUTE")

# Process: Layer To KML (5)
arcpy.LayerToKML_conversion(yose_valley_rst05_hillshade__2_, yose_valley_hillshade_low_kmz, "0", "NO_COMPOSITE", "DEFAULT", "21504", "300", "ABSOLUTE")

# Process: Layer To KML (6)
arcpy.LayerToKML_conversion(Possible_Climbing_Areas_Class, PossibleClimbingSlopesLowres_kmz__3_, "0", "NO_COMPOSITE", "DEFAULT", "10240", "300", "CLAMPED_TO_GROUND")

