# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# junk2.py
# Created on: 2020-01-17 19:32:52.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: junk2 <sample_rst> <Slope_Raster> <Final_Slope> <v_slope_min_value> <Con_Con_Zona1> <Expression> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("D:/gis/GIS_Coursera/5. Geospatial Analysis Project/Work/Yose Best Climbing Places.tbx")

# Script arguments
sample_rst = arcpy.GetParameterAsText(0)
if sample_rst == '#' or not sample_rst:
    sample_rst = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\helper_data.gdb\\sample_rst" # provide a default value if unspecified

Slope_Raster = arcpy.GetParameterAsText(1)
if Slope_Raster == '#' or not Slope_Raster:
    Slope_Raster = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Slope" # provide a default value if unspecified

Final_Slope = arcpy.GetParameterAsText(2)
if Final_Slope == '#' or not Final_Slope:
    Final_Slope = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Final_Slope" # provide a default value if unspecified

v_slope_min_value = arcpy.GetParameterAsText(3)
if v_slope_min_value == '#' or not v_slope_min_value:
    v_slope_min_value = "Value >= 45" # provide a default value if unspecified

Con_Con_Zona1 = arcpy.GetParameterAsText(4)
if Con_Con_Zona1 == '#' or not Con_Con_Zona1:
    Con_Con_Zona1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Con_Con_Zona1" # provide a default value if unspecified

Expression = arcpy.GetParameterAsText(5)
if Expression == '#' or not Expression:
    Expression = "Value >= 45" # provide a default value if unspecified

# Local variables:
Slope_Filtered = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Slope_Filtered"
Extract_AreaGreater1000__2_ = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Extract_AreaGreater1000"
Slope_Filtered2 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Slope_Filtered2"
Int_Con_Extr = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Int_Con_Extr"
Boundary_Extr = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Boundary_Extr"
Majorit_Boundary = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Majorit_Boundary"
Reclass_Slope = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Reclass_Slope"
Extract_AreaGreater1000 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Extract_AreaGreater1000"
sample_rst__3_ = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\helper_data.gdb\\sample_rst"
Slope_sample1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Slope_sample1"
Con_Slope_sa1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Con_Slope_sa1"
Input_true_raster_or_constant_value = "1"
Con_Con_Slop1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Con_Con_Slop1"
Expand_Con_I1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Expand_Con_C1"
RegionG_Expa1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\RegionG_Expa1"
ZonalGe_Expa12 = "C:\\GIS\\data\\scratch.gdb\\ZonalGe_Expa12"
Int_ZonalGe_1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Int_ZonalGe_1"
Extract_band13 = "C:\\GIS\\data\\scratch.gdb\\Extract_band13"
Con_Extract_1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Con_Extract_1"
Int_Con_Extr1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Int_Con_Extr1"
Boundar_band45 = "C:\\GIS\\data\\scratch.gdb\\Boundar_band45"
Majorit_Boun35 = "C:\\GIS\\data\\scratch.gdb\\Majorit_Boun35"
Reclass_Majo1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Reclass_Majo1"
Input_true_raster_or_constant_value__4_ = "1"
Con_Reclass_1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Con_Reclass_1"
RegionG_Con_2 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\RegionG_Con_1"
Extract_Regi2 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Extract_Regi1"
ZonalGe_Extr2 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\ZonalGe_Extr1"
Input_true_raster_or_constant_value__3_ = "1"
Con_ZonalGe_1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\Con_ZonalGe_1"
RasterT_Con_Con1 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\RasterT_Con_Con1"
Output_Extent_File = "C:\\GIS\\data\\scratch.gdb\\Extent"
AOI = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\helper_data.gdb\\AOI"
AOI_Buffer = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\AOI_Buffer"
AOI_Buffer_PolygonToRaster = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\AOI_Buffer_PolygonToRaster"
n37_w120_1arc_v2_tif = "n37_w120_1arc_v2.tif"
SRTM_reproject = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\SRTM_reproject"
SRTM_outside = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\helper_data.gdb\\SRTM_outside"
AOI_Buffer_PolygonToRaster2 = "C:\\Users\\suns\\Documents\\ArcGIS\\Default1.gdb\\AOI_Buffer_PolygonToRaster2"
SRTM_inside = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\helper_data.gdb\\SRTM_inside"

# Set Geoprocessing environments
arcpy.env.cellSize = SRTM_outside

# Process: Slope
arcpy.Slope_3d(sample_rst, Slope_Raster, "DEGREE", "1", "PLANAR", "METER")

# Process: Con
arcpy.gp.Con_sa(Slope_Raster, Slope_Raster, Slope_Filtered, "", v_slope_min_value)

# Process: Clean Filtered Slope Area (2)
arcpy.gp.toolbox = "D:/gis/GIS_Coursera/5. Geospatial Analysis Project/Work/Yose Best Climbing Places.tbx";
# Warning: the toolbox D:/gis/GIS_Coursera/5. Geospatial Analysis Project/Work/Yose Best Climbing Places.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.CleanFilteredSlopeArea(...) with arcpy.CleanFilteredSlopeArea_ALIAS(...)
arcpy.gp.CleanFilteredSlopeArea(Slope_Filtered, "Value  > 1000", Extract_AreaGreater1000__2_)

# Process: Con (2)
arcpy.gp.Con_sa(Extract_AreaGreater1000__2_, Slope_Filtered, Slope_Filtered2, "", "Value >= 45")

# Process: Int
arcpy.gp.Int_sa(Slope_Filtered2, Int_Con_Extr)

# Process: Boundary Clean
arcpy.gp.BoundaryClean_sa(Int_Con_Extr, Boundary_Extr, "DESCEND", "TWO_WAY")

# Process: Majority Filter
arcpy.gp.MajorityFilter_sa(Boundary_Extr, Majorit_Boundary, "FOUR", "MAJORITY")

# Process: Reclassify
arcpy.gp.Reclassify_sa(Majorit_Boundary, "VALUE", "45 55 55;55 65 65;65 75 75;75 85 85;85 89 90", Reclass_Slope, "DATA")

# Process: Clean Filtered Slope Area
arcpy.gp.toolbox = "D:/gis/GIS_Coursera/5. Geospatial Analysis Project/Work/Yose Best Climbing Places.tbx";
# Warning: the toolbox D:/gis/GIS_Coursera/5. Geospatial Analysis Project/Work/Yose Best Climbing Places.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.CleanFilteredSlopeArea(...) with arcpy.CleanFilteredSlopeArea_ALIAS(...)
arcpy.gp.CleanFilteredSlopeArea(Reclass_Slope, "Value  > 1000", Extract_AreaGreater1000)

# Process: Con - Clean slope outside
arcpy.gp.Con_sa(Extract_AreaGreater1000, Reclass_Slope, Final_Slope, "", "")

# Process: Slope (2)
arcpy.Slope_3d(sample_rst__3_, Slope_sample1, "DEGREE", "1", "PLANAR", "METER")

# Process: Con (3)
arcpy.gp.Con_sa(Slope_sample1, Slope_sample1, Con_Slope_sa1, "", Expression)

# Process: Con (6)
arcpy.gp.Con_sa(Con_Slope_sa1, Input_true_raster_or_constant_value, Con_Con_Slop1, "", "Value >= 45")

# Process: Expand
arcpy.gp.Expand_sa(Con_Con_Slop1, Expand_Con_I1, "5", "1")

# Process: Region Group (6)
arcpy.gp.RegionGroup_sa(Expand_Con_I1, RegionG_Expa1, "EIGHT", "WITHIN", "ADD_LINK", "")

# Process: Zonal Geometry (3)
arcpy.gp.ZonalGeometry_sa(RegionG_Expa1, "VALUE", ZonalGe_Expa12, "AREA", "0.5")

# Process: Int (2)
arcpy.gp.Int_sa(ZonalGe_Expa12, Int_ZonalGe_1)

# Process: Extract by Attributes (5)
arcpy.gp.ExtractByAttributes_sa(Int_ZonalGe_1, "Value  > 1000", Extract_band13)

# Process: Con (4)
arcpy.gp.Con_sa(Extract_band13, Con_Slope_sa1, Con_Extract_1, "", "")

# Process: Int (3)
arcpy.gp.Int_sa(Con_Extract_1, Int_Con_Extr1)

# Process: Boundary Clean (4)
arcpy.gp.BoundaryClean_sa(Int_Con_Extr1, Boundar_band45, "DESCEND", "TWO_WAY")

# Process: Majority Filter (2)
arcpy.gp.MajorityFilter_sa(Boundar_band45, Majorit_Boun35, "FOUR", "MAJORITY")

# Process: Reclassify (2)
arcpy.gp.Reclassify_sa(Majorit_Boun35, "VALUE", "45 55 55;55 65 65;65 75 75;75 85 85;85 89 90", Reclass_Majo1, "DATA")

# Process: Con (8)
arcpy.gp.Con_sa(Reclass_Majo1, Input_true_raster_or_constant_value__4_, Con_Reclass_1, "", "")

# Process: Region Group (5)
arcpy.gp.RegionGroup_sa(Con_Reclass_1, RegionG_Con_2, "EIGHT", "WITHIN", "ADD_LINK", "")

# Process: Extract by Attributes (3)
arcpy.gp.ExtractByAttributes_sa(RegionG_Con_2, "Value  > 10", Extract_Regi2)

# Process: Zonal Geometry (2)
arcpy.gp.ZonalGeometry_sa(Extract_Regi2, "VALUE", ZonalGe_Extr2, "AREA", "0.5")

# Process: Con (5)
arcpy.gp.Con_sa(ZonalGe_Extr2, Input_true_raster_or_constant_value__3_, Con_ZonalGe_1, "", "VALUE > 1000")

# Process: Con (7)
arcpy.gp.Con_sa(Con_ZonalGe_1, Reclass_Majo1, Con_Con_Zona1, "", "")

# Process: Raster to Polygon
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolygon_conversion(Con_Con_Zona1, RasterT_Con_Con1, "NO_SIMPLIFY", "VALUE", "SINGLE_OUTER_PART", "")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

# Process: Eliminate Polygon Part
tempEnvironment0 = arcpy.env.newPrecision
arcpy.env.newPrecision = "SINGLE"
tempEnvironment1 = arcpy.env.autoCommit
arcpy.env.autoCommit = "1000"
tempEnvironment2 = arcpy.env.XYResolution
arcpy.env.XYResolution = ""
tempEnvironment3 = arcpy.env.processingServerUser
arcpy.env.processingServerUser = ""
tempEnvironment4 = arcpy.env.XYDomain
arcpy.env.XYDomain = ""
tempEnvironment5 = arcpy.env.processingServerPassword
arcpy.env.processingServerPassword = ""
tempEnvironment6 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = "C:\\Users\\suns\\Documents\\ArcGIS\\Default.gdb"
tempEnvironment7 = arcpy.env.cartographicPartitions
arcpy.env.cartographicPartitions = ""
tempEnvironment8 = arcpy.env.terrainMemoryUsage
arcpy.env.terrainMemoryUsage = "false"
tempEnvironment9 = arcpy.env.MTolerance
arcpy.env.MTolerance = ""
tempEnvironment10 = arcpy.env.compression
arcpy.env.compression = "LZ77"
tempEnvironment11 = arcpy.env.coincidentPoints
arcpy.env.coincidentPoints = "MEAN"
tempEnvironment12 = arcpy.env.randomGenerator
arcpy.env.randomGenerator = "0 ACM599"
tempEnvironment13 = arcpy.env.outputCoordinateSystem
arcpy.env.outputCoordinateSystem = ""
tempEnvironment14 = arcpy.env.rasterStatistics
arcpy.env.rasterStatistics = "STATISTICS 1 1"
tempEnvironment15 = arcpy.env.ZDomain
arcpy.env.ZDomain = ""
tempEnvironment16 = arcpy.env.cellSizeProjectionMethod
arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
tempEnvironment17 = arcpy.env.transferDomains
arcpy.env.transferDomains = "false"
tempEnvironment18 = arcpy.env.maintainAttachments
arcpy.env.maintainAttachments = "true"
tempEnvironment19 = arcpy.env.resamplingMethod
arcpy.env.resamplingMethod = "NEAREST"
tempEnvironment20 = arcpy.env.snapRaster
arcpy.env.snapRaster = ""
tempEnvironment21 = arcpy.env.projectCompare
arcpy.env.projectCompare = "NONE"
tempEnvironment22 = arcpy.env.cartographicCoordinateSystem
arcpy.env.cartographicCoordinateSystem = "PROJCS['NAD_1983_UTM_Zone_11N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-117.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]],VERTCS['NAVD88 height',VDATUM['North American Vertical Datum 1988'],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['metre',1.0]]"
tempEnvironment23 = arcpy.env.configKeyword
arcpy.env.configKeyword = ""
tempEnvironment24 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Same As Input"
tempEnvironment25 = arcpy.env.qualifiedFieldNames
arcpy.env.qualifiedFieldNames = "true"
tempEnvironment26 = arcpy.env.tileSize
arcpy.env.tileSize = "128 128"
tempEnvironment27 = arcpy.env.parallelProcessingFactor
arcpy.env.parallelProcessingFactor = ""
tempEnvironment28 = arcpy.env.pyramid
arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
tempEnvironment29 = arcpy.env.referenceScale
arcpy.env.referenceScale = ""
tempEnvironment30 = arcpy.env.processingServer
arcpy.env.processingServer = ""
tempEnvironment31 = arcpy.env.extent
arcpy.env.extent = "DEFAULT"
tempEnvironment32 = arcpy.env.XYTolerance
arcpy.env.XYTolerance = ""
tempEnvironment33 = arcpy.env.tinSaveVersion
arcpy.env.tinSaveVersion = "CURRENT"
tempEnvironment34 = arcpy.env.nodata
arcpy.env.nodata = "NONE"
tempEnvironment35 = arcpy.env.MDomain
arcpy.env.MDomain = ""
tempEnvironment36 = arcpy.env.spatialGrid1
arcpy.env.spatialGrid1 = "0"
tempEnvironment37 = arcpy.env.cellSize
arcpy.env.cellSize = "MAXOF"
tempEnvironment38 = arcpy.env.outputZValue
arcpy.env.outputZValue = ""
tempEnvironment39 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Same As Input"
tempEnvironment40 = arcpy.env.geographicTransformations
arcpy.env.geographicTransformations = "NAD_1927_To_NAD_1983_NADCON;NAD_1927_To_NAD_1983_NADCON;NAD_1927_To_NAD_1983_NADCON;NAD_1927_To_NAD_1983_NADCON"
tempEnvironment41 = arcpy.env.spatialGrid2
arcpy.env.spatialGrid2 = "0"
tempEnvironment42 = arcpy.env.ZResolution
arcpy.env.ZResolution = ""
tempEnvironment43 = arcpy.env.mask
arcpy.env.mask = ""
tempEnvironment44 = arcpy.env.spatialGrid3
arcpy.env.spatialGrid3 = "0"
tempEnvironment45 = arcpy.env.maintainSpatialIndex
arcpy.env.maintainSpatialIndex = "false"
tempEnvironment46 = arcpy.env.workspace
arcpy.env.workspace = "C:\\Users\\suns\\Documents\\ArcGIS\\Default.gdb"
tempEnvironment47 = arcpy.env.MResolution
arcpy.env.MResolution = ""
tempEnvironment48 = arcpy.env.derivedPrecision
arcpy.env.derivedPrecision = "HIGHEST"
tempEnvironment49 = arcpy.env.ZTolerance
arcpy.env.ZTolerance = ""
arcpy.EliminatePolygonPart_management(RasterT_Con_Con1, Output_Extent_File, "AREA", "20000 SquareMeters", "0", "CONTAINED_ONLY")
arcpy.env.newPrecision = tempEnvironment0
arcpy.env.autoCommit = tempEnvironment1
arcpy.env.XYResolution = tempEnvironment2
arcpy.env.processingServerUser = tempEnvironment3
arcpy.env.XYDomain = tempEnvironment4
arcpy.env.processingServerPassword = tempEnvironment5
arcpy.env.scratchWorkspace = tempEnvironment6
arcpy.env.cartographicPartitions = tempEnvironment7
arcpy.env.terrainMemoryUsage = tempEnvironment8
arcpy.env.MTolerance = tempEnvironment9
arcpy.env.compression = tempEnvironment10
arcpy.env.coincidentPoints = tempEnvironment11
arcpy.env.randomGenerator = tempEnvironment12
arcpy.env.outputCoordinateSystem = tempEnvironment13
arcpy.env.rasterStatistics = tempEnvironment14
arcpy.env.ZDomain = tempEnvironment15
arcpy.env.cellSizeProjectionMethod = tempEnvironment16
arcpy.env.transferDomains = tempEnvironment17
arcpy.env.maintainAttachments = tempEnvironment18
arcpy.env.resamplingMethod = tempEnvironment19
arcpy.env.snapRaster = tempEnvironment20
arcpy.env.projectCompare = tempEnvironment21
arcpy.env.cartographicCoordinateSystem = tempEnvironment22
arcpy.env.configKeyword = tempEnvironment23
arcpy.env.outputZFlag = tempEnvironment24
arcpy.env.qualifiedFieldNames = tempEnvironment25
arcpy.env.tileSize = tempEnvironment26
arcpy.env.parallelProcessingFactor = tempEnvironment27
arcpy.env.pyramid = tempEnvironment28
arcpy.env.referenceScale = tempEnvironment29
arcpy.env.processingServer = tempEnvironment30
arcpy.env.extent = tempEnvironment31
arcpy.env.XYTolerance = tempEnvironment32
arcpy.env.tinSaveVersion = tempEnvironment33
arcpy.env.nodata = tempEnvironment34
arcpy.env.MDomain = tempEnvironment35
arcpy.env.spatialGrid1 = tempEnvironment36
arcpy.env.cellSize = tempEnvironment37
arcpy.env.outputZValue = tempEnvironment38
arcpy.env.outputMFlag = tempEnvironment39
arcpy.env.geographicTransformations = tempEnvironment40
arcpy.env.spatialGrid2 = tempEnvironment41
arcpy.env.ZResolution = tempEnvironment42
arcpy.env.mask = tempEnvironment43
arcpy.env.spatialGrid3 = tempEnvironment44
arcpy.env.maintainSpatialIndex = tempEnvironment45
arcpy.env.workspace = tempEnvironment46
arcpy.env.MResolution = tempEnvironment47
arcpy.env.derivedPrecision = tempEnvironment48
arcpy.env.ZTolerance = tempEnvironment49

# Process: Buffer
arcpy.Buffer_analysis(AOI, AOI_Buffer, "-20 Meters", "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Polygon to Raster
arcpy.PolygonToRaster_conversion(AOI_Buffer, "OBJECTID", AOI_Buffer_PolygonToRaster, "CELL_CENTER", "NONE", "37")

# Process: Project Raster
arcpy.ProjectRaster_management(n37_w120_1arc_v2_tif, SRTM_reproject, "PROJCS['NAD_1983_UTM_Zone_11N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-117.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "NEAREST", "28.2636157312116 28.2636157312114", "WGS_1984_(ITRF00)_To_NAD_1983", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NO_VERTICAL")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("Con(IsNull(\"%AOI_Buffer_PolygonToRaster%\"), \"%SRTM_reproject%\")", SRTM_outside)

# Process: Polygon to Raster (2)
arcpy.PolygonToRaster_conversion(AOI, "OBJECTID", AOI_Buffer_PolygonToRaster2, "CELL_CENTER", "NONE", "370")

# Process: Raster Calculator (2)
arcpy.gp.RasterCalculator_sa("Con((\"%AOI_Buffer_PolygonToRaster2%\"), \"%SRTM_reproject%\")", SRTM_inside)

