# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# make_raster_from_lidar_and_aoi.py
# Created on: 2020-01-19 18:54:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: make_raster_from_lidar_and_aoi <yose_valley_tiles_rst05> <AOI> <Ground_Tiles> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
yose_valley_tiles_rst05 = arcpy.GetParameterAsText(0)
if yose_valley_tiles_rst05 == '#' or not yose_valley_tiles_rst05:
    yose_valley_tiles_rst05 = "c:\\gis\\scratch.gdb\\gtiles_lasda" # provide a default value if unspecified

AOI = arcpy.GetParameterAsText(1)

Ground_Tiles = arcpy.GetParameterAsText(2)
if Ground_Tiles == '#' or not Ground_Tiles:
    Ground_Tiles = "C:\\GIS" # provide a default value if unspecified

# Local variables:
yose_valley_las_grnd_lasd = "C:\\GIS\\GIS_LasDataset.lasd"
yose_valley_las_grnd_lasd__2_ = yose_valley_las_grnd_lasd

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"

# Process: Create LAS Dataset
arcpy.CreateLasDataset_management("C:\\GIS", yose_valley_las_grnd_lasd, "NO_RECURSION", "# <None> Soft_Clip", "PROJCS['NAD_1983_UTM_Zone_11N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-117.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]],VERTCS['NAVD_1988',VDATUM['North_American_Vertical_Datum_1988'],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]]", "COMPUTE_STATS", "RELATIVE_PATHS", "FILES_MISSING_PROJECTION")

# Process: Add Files to LAS Dataset
arcpy.AddFilesToLasDataset_management(yose_valley_las_grnd_lasd, "", "NO_RECURSION", "# <None> Soft_Clip")

# Process: LAS Dataset to Raster
arcpy.LasDatasetToRaster_conversion(yose_valley_las_grnd_lasd__2_, yose_valley_tiles_rst05, "ELEVATION", "", "FLOAT", "CELLSIZE", "0.5", "1")

