# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# prepare_valley_data.py
# Created on: 2020-01-17 19:23:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: prepare_valley_data <data> <v_valley_gdb_name> <v_park_gdb_name> <valley_data_gdb> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("D:/gis/GIS_Coursera/5. Geospatial Analysis Project/Work/Yose Best Climbing Places.tbx")

# Script arguments
data = arcpy.GetParameterAsText(0)
if data == '#' or not data:
    data = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data" # provide a default value if unspecified

v_valley_gdb_name = arcpy.GetParameterAsText(1)
if v_valley_gdb_name == '#' or not v_valley_gdb_name:
    v_valley_gdb_name = "valley_data" # provide a default value if unspecified

v_park_gdb_name = arcpy.GetParameterAsText(2)
if v_park_gdb_name == '#' or not v_park_gdb_name:
    v_park_gdb_name = "park_data" # provide a default value if unspecified

valley_data_gdb = arcpy.GetParameterAsText(3)
if valley_data_gdb == '#' or not valley_data_gdb:
    valley_data_gdb = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\valley_data.gdb" # provide a default value if unspecified

# Local variables:
park_data_gdb = data
AOI = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\helper_data.gdb\\AOI"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"

# Process: Create GDB And Import Park Data
arcpy.gp.toolbox = "D:/gis/GIS_Coursera/5. Geospatial Analysis Project/Work/Yose Best Climbing Places.tbx";
# Warning: the toolbox D:/gis/GIS_Coursera/5. Geospatial Analysis Project/Work/Yose Best Climbing Places.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.CreateGDBAndImportParkData(...) with arcpy.CreateGDBAndImportParkData_ALIAS(...)
arcpy.gp.CreateGDBAndImportParkData(data, v_park_gdb_name)

# Process: Create File GDB
arcpy.CreateFileGDB_management(data, v_valley_gdb_name, "CURRENT")

# Process: Iterate And Clip Valley Data
arcpy.gp.toolbox = "D:/gis/GIS_Coursera/5. Geospatial Analysis Project/Work/Yose Best Climbing Places.tbx";
# Warning: the toolbox D:/gis/GIS_Coursera/5. Geospatial Analysis Project/Work/Yose Best Climbing Places.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.IterateAndClipValleyData(...) with arcpy.IterateAndClipValleyData_ALIAS(...)
arcpy.gp.IterateAndClipValleyData(park_data_gdb, AOI)

