# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# prepare_valley_data.py
# Created on: 2020-01-19 18:56:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: prepare_valley_data <v_valley_gdb_name> <v_park_gdb_name> <valley_data_gdb> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("D:/gis/GIS_Coursera/Yosemite/model/Yose Best Climbing PlacesCopy.tbx")

# Script arguments
v_valley_gdb_name = arcpy.GetParameterAsText(0)
if v_valley_gdb_name == '#' or not v_valley_gdb_name:
    v_valley_gdb_name = "valley_data" # provide a default value if unspecified

v_park_gdb_name = arcpy.GetParameterAsText(1)
if v_park_gdb_name == '#' or not v_park_gdb_name:
    v_park_gdb_name = "park_data" # provide a default value if unspecified

valley_data_gdb = arcpy.GetParameterAsText(2)
if valley_data_gdb == '#' or not valley_data_gdb:
    valley_data_gdb = "C:\\GIS\\valley_data.gdb" # provide a default value if unspecified

# Local variables:
Data_Folder = ""
park_data_gdb = Data_Folder
AOI = ""

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"

# Process: Create GDB And Import Park Data
arcpy.gp.toolbox = "D:/gis/GIS_Coursera/Yosemite/model/Yose Best Climbing PlacesCopy.tbx";
# Warning: the toolbox D:/gis/GIS_Coursera/Yosemite/model/Yose Best Climbing PlacesCopy.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.CreateGDBAndImportParkData(...) with arcpy.CreateGDBAndImportParkData_ALIAS(...)
arcpy.gp.CreateGDBAndImportParkData(v_park_gdb_name, Data_Folder)

# Process: Create File GDB
arcpy.CreateFileGDB_management(Data_Folder, v_valley_gdb_name, "CURRENT")

# Process: Iterate And Clip Valley Data
arcpy.gp.toolbox = "D:/gis/GIS_Coursera/Yosemite/model/Yose Best Climbing PlacesCopy.tbx";
# Warning: the toolbox D:/gis/GIS_Coursera/Yosemite/model/Yose Best Climbing PlacesCopy.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.IterateAndClipValleyData(...) with arcpy.IterateAndClipValleyData_ALIAS(...)
arcpy.gp.IterateAndClipValleyData(park_data_gdb, AOI)

