# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# slope_stream_length.py
# Created on: 2020-01-17 19:25:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: slope_stream_length <Clipped_Streams_Elevation> <yose_valley_tiles_rst05> <Stream_Lines> <Pos_Climbing_Buffer> <Clipped_Streams> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Clipped_Streams_Elevation = arcpy.GetParameterAsText(0)
if Clipped_Streams_Elevation == '#' or not Clipped_Streams_Elevation:
    Clipped_Streams_Elevation = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Clipped_Streams_Elevation" # provide a default value if unspecified

yose_valley_tiles_rst05 = arcpy.GetParameterAsText(1)
if yose_valley_tiles_rst05 == '#' or not yose_valley_tiles_rst05:
    yose_valley_tiles_rst05 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\results.gdb\\yose_valley_tiles_rst05" # provide a default value if unspecified

Stream_Lines = arcpy.GetParameterAsText(2)
if Stream_Lines == '#' or not Stream_Lines:
    Stream_Lines = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\results.gdb\\Stream_Lines" # provide a default value if unspecified

Pos_Climbing_Buffer = arcpy.GetParameterAsText(3)
if Pos_Climbing_Buffer == '#' or not Pos_Climbing_Buffer:
    Pos_Climbing_Buffer = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\results.gdb\\Pos_Climbing_Buffer" # provide a default value if unspecified

Clipped_Streams = arcpy.GetParameterAsText(4)
if Clipped_Streams == '#' or not Clipped_Streams:
    Clipped_Streams = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Clipped_Streams" # provide a default value if unspecified

# Local variables:
RasterT_Pos_Cli1 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\RasterT_Pos_Cli1"
StreamLines_Clip = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\StreamLines_Clip"
ZonalSt_Stre2 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\ZonalSt_Stre2"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"

# Process: Raster to Polygon
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolygon_conversion(Pos_Climbing_Buffer, RasterT_Pos_Cli1, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

# Process: Clip
arcpy.Clip_analysis(Stream_Lines, RasterT_Pos_Cli1, StreamLines_Clip, "")

# Process: Zonal Statistics
arcpy.gp.ZonalStatistics_sa(StreamLines_Clip, "arcid", yose_valley_tiles_rst05, ZonalSt_Stre2, "RANGE", "DATA")

# Process: Reclassify (3)
arcpy.gp.Reclassify_sa(ZonalSt_Stre2, "VALUE", "0 100 1;100 200 2;200 300 3;300 400 4;400 500 5;500 600 6;600 700 7;700 800 8;800 900 9", Clipped_Streams_Elevation, "DATA")

# Process: Raster to Polyline
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolyline_conversion(Clipped_Streams_Elevation, Clipped_Streams, "ZERO", "0", "NO_SIMPLIFY", "VALUE")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

