# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# slope_stream_length.py
# Created on: 2020-01-19 19:06:56.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: slope_stream_length <Clipped_Streams_Elevation> <yose_valley_tiles_rst05> <Stream_Lines> <Pos_Climbing_Buffer> <Clipped_Streams> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Clipped_Streams_Elevation = arcpy.GetParameterAsText(0)

yose_valley_tiles_rst05 = arcpy.GetParameterAsText(1)

Stream_Lines = arcpy.GetParameterAsText(2)

Pos_Climbing_Buffer = arcpy.GetParameterAsText(3)

Clipped_Streams = arcpy.GetParameterAsText(4)

# Local variables:
RasterT_Pos_Cli1 = ""
StreamLines_Clip = ""
ZonalSt_Stre2 = ""

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"

# Process: Raster to Polygon
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolygon_conversion(Pos_Climbing_Buffer, RasterT_Pos_Cli1, "SIMPLIFY", "", "SINGLE_OUTER_PART", "")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

# Process: Clip
arcpy.Clip_analysis(Stream_Lines, RasterT_Pos_Cli1, StreamLines_Clip, "")

# Process: Zonal Statistics
arcpy.gp.ZonalStatistics_sa(StreamLines_Clip, "", yose_valley_tiles_rst05, ZonalSt_Stre2, "RANGE", "DATA")

# Process: Reclassify (3)
arcpy.gp.Reclassify_sa(ZonalSt_Stre2, "", "0 100 1;100 200 2;200 300 3;300 400 4;400 500 5;500 600 6;600 700 7;700 800 8;800 900 9", Clipped_Streams_Elevation, "DATA")

# Process: Raster to Polyline
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolyline_conversion(Clipped_Streams_Elevation, Clipped_Streams, "ZERO", "0", "NO_SIMPLIFY", "")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

