# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# slope_analysis.py
# Created on: 2020-01-19 19:38:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: slope_analysis <yose_valley_tiles_rst05> <Slope_Raster> <v_slope_min_value> <v_area_value> <Slope_Filtered> <Possible_Climbing_Areas> <Pos_Climbing_Buffer> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
yose_valley_tiles_rst05 = arcpy.GetParameterAsText(0)

Slope_Raster = arcpy.GetParameterAsText(1)

v_slope_min_value = arcpy.GetParameterAsText(2)
if v_slope_min_value == '#' or not v_slope_min_value:
    v_slope_min_value = "Value >= 45" # provide a default value if unspecified

v_area_value = arcpy.GetParameterAsText(3)
if v_area_value == '#' or not v_area_value:
    v_area_value = "Value  > 1000" # provide a default value if unspecified

Slope_Filtered = arcpy.GetParameterAsText(4)

Possible_Climbing_Areas = arcpy.GetParameterAsText(5)
if Possible_Climbing_Areas == '#' or not Possible_Climbing_Areas:
    Possible_Climbing_Areas = "C:\\GIS\\scratch.gdb\\Possible_Climbing_Areas" # provide a default value if unspecified

Pos_Climbing_Buffer = arcpy.GetParameterAsText(6)
if Pos_Climbing_Buffer == '#' or not Pos_Climbing_Buffer:
    Pos_Climbing_Buffer = "C:\\GIS\\scratch.gdb\\Pos_Climbing_Buffer" # provide a default value if unspecified

# Local variables:
Input_true_raster_or_constant_value__6_ = "1"
Slope_Filtered_1 = ""
Expand_Slope = ""
RegionG_Expand = ""
ZonalGe_RegionG = ""
Int_ZonalGe = ""
Extract_AreaGreater1000 = ""
Slope_Filtered2 = ""
Int_Con_Extr__2_ = ""
Boundary_Extr__2_ = ""
Majorit_Boundary__2_ = ""
Input_true_raster_or_constant_value__3_ = "1"
Con_Majorit_1 = ""
RegionG_Con_2__3_ = ""
Extract_Regi2__3_ = ""
ZonalGe_Extr2__3_ = ""
Input_true_raster_or_constant_value__4_ = "1"
Con_ZonalGe_1__3_ = ""
Pos_Climbing_Zones = ""
Output_direction_raster = ""
temp = ""
Input_true_raster_or_constant_value__2_ = "1"
Con_Pos_Clim1 = ""
EucDist_Fina1 = ""
Input_true_raster_or_constant_value = "1"
Con_EucDist_1 = ""
rastercalc = "C:\\GIS\\scratch.gdb\\rastercalc"
Input_true_raster_or_constant_value__5_ = "1"
Con_rasterca1 = "C:\\GIS\\scratch.gdb\\Con_rasterca1"
RasterT_Con_ras1 = "C:\\GIS\\scratch.gdb\\RasterT_Con_ras1"
Slope_Poly = "C:\\GIS\\scratch.gdb\\RasterT_Con_ras1_EliminatePo"
Final_Slope_PolyB_Dissolve = "C:\\GIS\\scratch.gdb\\Final_Slope_PolyB_Dissolve"
Final_Slope_PolyB_Dissolve_B = "C:\\GIS\\scratch.gdb\\Final_Slope_PolyB_Dissolve_B"
Final_Slope_PolyB_Dissolve_B1 = "C:\\GIS\\scratch.gdb\\Final_Slope_PolyB_Dissolve_B1"
Input_true_raster_or_constant_value__7_ = "1"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"

# Process: Slope
arcpy.Slope_3d(yose_valley_tiles_rst05, Slope_Raster, "DEGREE", "1", "PLANAR", "METER")

# Process: Con
arcpy.gp.Con_sa(Slope_Raster, Slope_Raster, Slope_Filtered, "", v_slope_min_value)

# Process: Con (3)
arcpy.gp.Con_sa(Slope_Filtered, Input_true_raster_or_constant_value__6_, Slope_Filtered_1, "", "")

# Process: Expand
arcpy.gp.Expand_sa(Slope_Filtered_1, Expand_Slope, "5", "1")

# Process: Region Group
arcpy.gp.RegionGroup_sa(Expand_Slope, RegionG_Expand, "EIGHT", "WITHIN", "ADD_LINK", "")

# Process: Zonal Geometry
arcpy.gp.ZonalGeometry_sa(RegionG_Expand, "", ZonalGe_RegionG, "AREA", "0.5")

# Process: Int (2)
arcpy.gp.Int_sa(ZonalGe_RegionG, Int_ZonalGe)

# Process: Extract by Attributes (2)
arcpy.gp.ExtractByAttributes_sa(Int_ZonalGe, v_area_value, Extract_AreaGreater1000)

# Process: Con (2)
arcpy.gp.Con_sa(Extract_AreaGreater1000, Slope_Filtered, Slope_Filtered2, "", "Value >= 45")

# Process: Int (3)
arcpy.gp.Int_sa(Slope_Filtered2, Int_Con_Extr__2_)

# Process: Boundary Clean (2)
arcpy.gp.BoundaryClean_sa(Int_Con_Extr__2_, Boundary_Extr__2_, "DESCEND", "TWO_WAY")

# Process: Majority Filter (2)
arcpy.gp.MajorityFilter_sa(Boundary_Extr__2_, Majorit_Boundary__2_, "FOUR", "MAJORITY")

# Process: Con (5)
arcpy.gp.Con_sa(Majorit_Boundary__2_, Input_true_raster_or_constant_value__3_, Con_Majorit_1, "", "")

# Process: Region Group (3)
arcpy.gp.RegionGroup_sa(Con_Majorit_1, RegionG_Con_2__3_, "EIGHT", "WITHIN", "ADD_LINK", "")

# Process: Extract by Attributes (3)
arcpy.gp.ExtractByAttributes_sa(RegionG_Con_2__3_, "Value  > 10", Extract_Regi2__3_)

# Process: Zonal Geometry (2)
arcpy.gp.ZonalGeometry_sa(Extract_Regi2__3_, "", ZonalGe_Extr2__3_, "AREA", "0.5")

# Process: Con (4)
arcpy.gp.Con_sa(ZonalGe_Extr2__3_, Input_true_raster_or_constant_value__4_, Con_ZonalGe_1__3_, "", "VALUE > 1000")

# Process: Con - Clean slope outside (3)
arcpy.gp.Con_sa(Con_ZonalGe_1__3_, Majorit_Boundary__2_, Pos_Climbing_Zones, "", "")

# Process: Euclidean Distance
arcpy.gp.EucDistance_sa(Pos_Climbing_Zones, EucDist_Fina1, "12", "0.5", Output_direction_raster, "PLANAR", "", temp)

# Process: Con (8)
arcpy.gp.Con_sa(Pos_Climbing_Zones, Input_true_raster_or_constant_value__2_, Con_Pos_Clim1, "", "")

# Process: Con (6)
arcpy.gp.Con_sa(EucDist_Fina1, Input_true_raster_or_constant_value, Con_EucDist_1, "", "")

# Process: Raster Calculator
arcpy.gp.RasterCalculator_sa("Con(IsNull(\"%Con_Pos_Clim1%\"),0,\"%Con_Pos_Clim1%\") + Con(IsNull(\"%Con_EucDist_1%\"),0,\"%Con_EucDist_1%\")", rastercalc)

# Process: Con (7)
arcpy.gp.Con_sa(rastercalc, Input_true_raster_or_constant_value__5_, Con_rasterca1, "", "Value = 1")

# Process: Raster to Polygon
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolygon_conversion(Con_rasterca1, RasterT_Con_ras1, "NO_SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

# Process: Eliminate Polygon Part Area > 2000
tempEnvironment0 = arcpy.env.newPrecision
arcpy.env.newPrecision = "SINGLE"
tempEnvironment1 = arcpy.env.autoCommit
arcpy.env.autoCommit = "1000"
tempEnvironment2 = arcpy.env.XYResolution
arcpy.env.XYResolution = ""
tempEnvironment3 = arcpy.env.processingServerUser
arcpy.env.processingServerUser = ""
tempEnvironment4 = arcpy.env.XYDomain
arcpy.env.XYDomain = ""
tempEnvironment5 = arcpy.env.processingServerPassword
arcpy.env.processingServerPassword = ""
tempEnvironment6 = arcpy.env.scratchWorkspace
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
tempEnvironment7 = arcpy.env.cartographicPartitions
arcpy.env.cartographicPartitions = ""
tempEnvironment8 = arcpy.env.terrainMemoryUsage
arcpy.env.terrainMemoryUsage = "false"
tempEnvironment9 = arcpy.env.MTolerance
arcpy.env.MTolerance = ""
tempEnvironment10 = arcpy.env.compression
arcpy.env.compression = "LZ77"
tempEnvironment11 = arcpy.env.coincidentPoints
arcpy.env.coincidentPoints = "MEAN"
tempEnvironment12 = arcpy.env.randomGenerator
arcpy.env.randomGenerator = "0 ACM599"
tempEnvironment13 = arcpy.env.outputCoordinateSystem
arcpy.env.outputCoordinateSystem = ""
tempEnvironment14 = arcpy.env.rasterStatistics
arcpy.env.rasterStatistics = "STATISTICS 1 1"
tempEnvironment15 = arcpy.env.ZDomain
arcpy.env.ZDomain = ""
tempEnvironment16 = arcpy.env.cellSizeProjectionMethod
arcpy.env.cellSizeProjectionMethod = "CONVERT_UNITS"
tempEnvironment17 = arcpy.env.transferDomains
arcpy.env.transferDomains = "false"
tempEnvironment18 = arcpy.env.maintainAttachments
arcpy.env.maintainAttachments = "true"
tempEnvironment19 = arcpy.env.resamplingMethod
arcpy.env.resamplingMethod = "NEAREST"
tempEnvironment20 = arcpy.env.snapRaster
arcpy.env.snapRaster = ""
tempEnvironment21 = arcpy.env.projectCompare
arcpy.env.projectCompare = "NONE"
tempEnvironment22 = arcpy.env.cartographicCoordinateSystem
arcpy.env.cartographicCoordinateSystem = "PROJCS['NAD_1983_UTM_Zone_11N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-117.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]],VERTCS['NAVD88 height',VDATUM['North American Vertical Datum 1988'],PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['metre',1.0]]"
tempEnvironment23 = arcpy.env.configKeyword
arcpy.env.configKeyword = ""
tempEnvironment24 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Same As Input"
tempEnvironment25 = arcpy.env.qualifiedFieldNames
arcpy.env.qualifiedFieldNames = "true"
tempEnvironment26 = arcpy.env.tileSize
arcpy.env.tileSize = "128 128"
tempEnvironment27 = arcpy.env.parallelProcessingFactor
arcpy.env.parallelProcessingFactor = ""
tempEnvironment28 = arcpy.env.pyramid
arcpy.env.pyramid = "PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP"
tempEnvironment29 = arcpy.env.referenceScale
arcpy.env.referenceScale = ""
tempEnvironment30 = arcpy.env.processingServer
arcpy.env.processingServer = ""
tempEnvironment31 = arcpy.env.extent
arcpy.env.extent = "DEFAULT"
tempEnvironment32 = arcpy.env.XYTolerance
arcpy.env.XYTolerance = ""
tempEnvironment33 = arcpy.env.tinSaveVersion
arcpy.env.tinSaveVersion = "CURRENT"
tempEnvironment34 = arcpy.env.nodata
arcpy.env.nodata = "NONE"
tempEnvironment35 = arcpy.env.MDomain
arcpy.env.MDomain = ""
tempEnvironment36 = arcpy.env.spatialGrid1
arcpy.env.spatialGrid1 = "0"
tempEnvironment37 = arcpy.env.cellSize
arcpy.env.cellSize = "MAXOF"
tempEnvironment38 = arcpy.env.outputZValue
arcpy.env.outputZValue = ""
tempEnvironment39 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Same As Input"
tempEnvironment40 = arcpy.env.geographicTransformations
arcpy.env.geographicTransformations = "NAD_1927_To_NAD_1983_NADCON;NAD_1927_To_NAD_1983_NADCON;NAD_1927_To_NAD_1983_NADCON;NAD_1927_To_NAD_1983_NADCON"
tempEnvironment41 = arcpy.env.spatialGrid2
arcpy.env.spatialGrid2 = "0"
tempEnvironment42 = arcpy.env.ZResolution
arcpy.env.ZResolution = ""
tempEnvironment43 = arcpy.env.mask
arcpy.env.mask = ""
tempEnvironment44 = arcpy.env.spatialGrid3
arcpy.env.spatialGrid3 = "0"
tempEnvironment45 = arcpy.env.maintainSpatialIndex
arcpy.env.maintainSpatialIndex = "false"
tempEnvironment46 = arcpy.env.workspace
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"
tempEnvironment47 = arcpy.env.MResolution
arcpy.env.MResolution = ""
tempEnvironment48 = arcpy.env.derivedPrecision
arcpy.env.derivedPrecision = "HIGHEST"
tempEnvironment49 = arcpy.env.ZTolerance
arcpy.env.ZTolerance = ""
arcpy.EliminatePolygonPart_management(RasterT_Con_ras1, Slope_Poly, "AREA", "2000 SquareMeters", "0", "CONTAINED_ONLY")
arcpy.env.newPrecision = tempEnvironment0
arcpy.env.autoCommit = tempEnvironment1
arcpy.env.XYResolution = tempEnvironment2
arcpy.env.processingServerUser = tempEnvironment3
arcpy.env.XYDomain = tempEnvironment4
arcpy.env.processingServerPassword = tempEnvironment5
arcpy.env.scratchWorkspace = tempEnvironment6
arcpy.env.cartographicPartitions = tempEnvironment7
arcpy.env.terrainMemoryUsage = tempEnvironment8
arcpy.env.MTolerance = tempEnvironment9
arcpy.env.compression = tempEnvironment10
arcpy.env.coincidentPoints = tempEnvironment11
arcpy.env.randomGenerator = tempEnvironment12
arcpy.env.outputCoordinateSystem = tempEnvironment13
arcpy.env.rasterStatistics = tempEnvironment14
arcpy.env.ZDomain = tempEnvironment15
arcpy.env.cellSizeProjectionMethod = tempEnvironment16
arcpy.env.transferDomains = tempEnvironment17
arcpy.env.maintainAttachments = tempEnvironment18
arcpy.env.resamplingMethod = tempEnvironment19
arcpy.env.snapRaster = tempEnvironment20
arcpy.env.projectCompare = tempEnvironment21
arcpy.env.cartographicCoordinateSystem = tempEnvironment22
arcpy.env.configKeyword = tempEnvironment23
arcpy.env.outputZFlag = tempEnvironment24
arcpy.env.qualifiedFieldNames = tempEnvironment25
arcpy.env.tileSize = tempEnvironment26
arcpy.env.parallelProcessingFactor = tempEnvironment27
arcpy.env.pyramid = tempEnvironment28
arcpy.env.referenceScale = tempEnvironment29
arcpy.env.processingServer = tempEnvironment30
arcpy.env.extent = tempEnvironment31
arcpy.env.XYTolerance = tempEnvironment32
arcpy.env.tinSaveVersion = tempEnvironment33
arcpy.env.nodata = tempEnvironment34
arcpy.env.MDomain = tempEnvironment35
arcpy.env.spatialGrid1 = tempEnvironment36
arcpy.env.cellSize = tempEnvironment37
arcpy.env.outputZValue = tempEnvironment38
arcpy.env.outputMFlag = tempEnvironment39
arcpy.env.geographicTransformations = tempEnvironment40
arcpy.env.spatialGrid2 = tempEnvironment41
arcpy.env.ZResolution = tempEnvironment42
arcpy.env.mask = tempEnvironment43
arcpy.env.spatialGrid3 = tempEnvironment44
arcpy.env.maintainSpatialIndex = tempEnvironment45
arcpy.env.workspace = tempEnvironment46
arcpy.env.MResolution = tempEnvironment47
arcpy.env.derivedPrecision = tempEnvironment48
arcpy.env.ZTolerance = tempEnvironment49

# Process: Dissolve
arcpy.Dissolve_management(Slope_Poly, Final_Slope_PolyB_Dissolve, "", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Buffer (3)
arcpy.Buffer_analysis(Final_Slope_PolyB_Dissolve, Final_Slope_PolyB_Dissolve_B, "-12 Meters", "FULL", "ROUND", "ALL", "", "PLANAR")

# Process: Polygon to Raster
arcpy.PolygonToRaster_conversion(Final_Slope_PolyB_Dissolve_B, "OBJECTID", Final_Slope_PolyB_Dissolve_B1, "CELL_CENTER", "NONE", "0.5")

# Process: Con (10)
arcpy.gp.Con_sa(Final_Slope_PolyB_Dissolve_B1, Input_true_raster_or_constant_value__7_, Pos_Climbing_Buffer, "", "")

# Process: Con (9)
arcpy.gp.Con_sa(Pos_Climbing_Buffer, Slope_Raster, Possible_Climbing_Areas, "", "")

