# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# slope_cliffs.py
# Created on: 2020-01-19 19:04:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: slope_cliffs <ProfileC> <yose_valley_rst05_hillshade> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
ProfileC = arcpy.GetParameterAsText(0)

yose_valley_rst05_hillshade = arcpy.GetParameterAsText(1)

# Local variables:
Curvature__3_ = ""
plan_curve = ""
profile_curve = ""
FocalSt_ProfileC = ""
Input_true_raster_or_constant_value__2_ = "1"
VALUE_>_46428__add_the_mean_and_the_standard_deviation__ = "VALUE > 46428"
RegionG_Prof1 = ""
Input_false_raster_or_constant_value = "1"
SetNull_Regi1 = ""

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"

# Process: Curvature
arcpy.gp.Curvature_sa(yose_valley_rst05_hillshade, Curvature__3_, "1", profile_curve, plan_curve)

# Process: Focal Statistics (2)
arcpy.gp.FocalStatistics_sa(profile_curve, FocalSt_ProfileC, "Rectangle 3 3 CELL", "RANGE", "DATA", "90")

# Process: Con (9)
arcpy.gp.Con_sa(FocalSt_ProfileC, Input_true_raster_or_constant_value__2_, ProfileC, "", VALUE_>_46428__add_the_mean_and_the_standard_deviation__)

# Process: Region Group
arcpy.gp.RegionGroup_sa(ProfileC, RegionG_Prof1, "EIGHT", "WITHIN", "ADD_LINK", "")

# Process: Set Null
arcpy.gp.SetNull_sa(RegionG_Prof1, Input_false_raster_or_constant_value, SetNull_Regi1, "Count < 41")

