# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# slope_cliffs.py
# Created on: 2020-01-17 19:24:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: slope_cliffs <ProfileC> <yose_valley_rst05_hillshade> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
ProfileC = arcpy.GetParameterAsText(0)
if ProfileC == '#' or not ProfileC:
    ProfileC = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\ProfileC" # provide a default value if unspecified

yose_valley_rst05_hillshade = arcpy.GetParameterAsText(1)
if yose_valley_rst05_hillshade == '#' or not yose_valley_rst05_hillshade:
    yose_valley_rst05_hillshade = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\final.gdb\\yose_valley_rst05_hillshade" # provide a default value if unspecified

# Local variables:
Curvature__2_ = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Curvature"
plan_curve = ""
profile_curve = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\Profile_curve"
FocalSt_ProfileC = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\FocalSt_ProfCurv"
Input_true_raster_or_constant_value__2_ = "1"
VALUE_>_46428__add_the_mean_and_the_standard_deviation__ = "VALUE > 46428"
RegionG_Prof1 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\RegionG_Prof1"
Input_false_raster_or_constant_value = "1"
SetNull_Regi1 = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb\\SetNull_Regi1"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"
arcpy.env.workspace = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\scratch.gdb"

# Process: Curvature
arcpy.gp.Curvature_sa(yose_valley_rst05_hillshade, Curvature__2_, "1", profile_curve, plan_curve)

# Process: Focal Statistics (2)
arcpy.gp.FocalStatistics_sa(profile_curve, FocalSt_ProfileC, "Rectangle 3 3 CELL", "RANGE", "DATA", "90")

# Process: Con (9)
arcpy.gp.Con_sa(FocalSt_ProfileC, Input_true_raster_or_constant_value__2_, ProfileC, "", VALUE_>_46428__add_the_mean_and_the_standard_deviation__)

# Process: Region Group
arcpy.gp.RegionGroup_sa(ProfileC, RegionG_Prof1, "EIGHT", "WITHIN", "ADD_LINK", "")

# Process: Set Null
arcpy.gp.SetNull_sa(RegionG_Prof1, Input_false_raster_or_constant_value, SetNull_Regi1, "Count < 41")

