# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# valley_data_euclidean_distance.py
# Created on: 2020-01-19 19:09:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: valley_data_euclidean_distance <Springs_EDist> <Trails_EDist> <Climb_EDist> <Rivers_EDist> <Parking_EDist> <AOI> <Roads_EDist> <Pos_Climbing_Areas> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
Springs_EDist = arcpy.GetParameterAsText(0)

Trails_EDist = arcpy.GetParameterAsText(1)

Climb_EDist = arcpy.GetParameterAsText(2)

Rivers_EDist = arcpy.GetParameterAsText(3)

Parking_EDist = arcpy.GetParameterAsText(4)

AOI = arcpy.GetParameterAsText(5)

Roads_EDist = arcpy.GetParameterAsText(6)

Pos_Climbing_Areas = arcpy.GetParameterAsText(7)

# Local variables:
YOSE_Parking_20190521_clp = ""
Barrier = ""
Output_direction_raster__3_ = ""
Output_back_direction_raster__3_ = ""
Rivers_clp = ""
Output_direction_raster__5_ = ""
Output_back_direction_raster__5_ = ""
Yosemite_Climbing_Areas_clp = ""
Output_direction_raster__6_ = ""
Output_back_direction_raster__6_ = ""
Trails_clp = ""
Output_direction_raster = ""
Output_back_direction_raster = ""
Springs_clp = ""
Output_back_direction_raster__4_ = ""
Output_direction_raster__4_ = ""
Yosemite_Roads_clp = ""
Output_direction_raster__8_ = ""
Output_back_direction_raster__8_ = ""

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"

# Process: Polygon To Line
arcpy.PolygonToLine_management(AOI, Barrier, "IGNORE_NEIGHBORS")

# Process: Euclidean Distance (3)
arcpy.gp.EucDistance_sa(YOSE_Parking_20190521_clp, Parking_EDist, "", Pos_Climbing_Areas, Output_direction_raster__3_, "PLANAR", Barrier, Output_back_direction_raster__3_)

# Process: Euclidean Distance (5)
arcpy.gp.EucDistance_sa(Rivers_clp, Rivers_EDist, "", Pos_Climbing_Areas, Output_direction_raster__5_, "PLANAR", Barrier, Output_back_direction_raster__5_)

# Process: Euclidean Distance (6)
arcpy.gp.EucDistance_sa(Yosemite_Climbing_Areas_clp, Climb_EDist, "", Pos_Climbing_Areas, Output_direction_raster__6_, "PLANAR", Barrier, Output_back_direction_raster__6_)

# Process: Euclidean Distance
arcpy.gp.EucDistance_sa(Trails_clp, Trails_EDist, "", Pos_Climbing_Areas, Output_direction_raster, "PLANAR", Barrier, Output_back_direction_raster)

# Process: Euclidean Distance (4)
arcpy.gp.EucDistance_sa(Springs_clp, Springs_EDist, "", Pos_Climbing_Areas, Output_direction_raster__4_, "PLANAR", Barrier, Output_back_direction_raster__4_)

# Process: Euclidean Distance (8)
arcpy.gp.EucDistance_sa(Yosemite_Roads_clp, Roads_EDist, "", Pos_Climbing_Areas, Output_direction_raster__8_, "PLANAR", Barrier, Output_back_direction_raster__8_)

