# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# weighted_overlay_simple.py
# Created on: 2020-01-17 19:27:15.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: weighted_overlay_simple <Clipped_Streams> <Pos_Climbing_Areas> <YosemiteV_Climbing> <Yose_Climbing_Lines> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Clipped_Streams = arcpy.GetParameterAsText(0)
if Clipped_Streams == '#' or not Clipped_Streams:
    Clipped_Streams = "C:\\GIS\\scratch.gdb\\Clipped_Streams" # provide a default value if unspecified

Pos_Climbing_Areas = arcpy.GetParameterAsText(1)
if Pos_Climbing_Areas == '#' or not Pos_Climbing_Areas:
    Pos_Climbing_Areas = "C:\\GIS\\scratch.gdb\\Pos_Climbing_Areas" # provide a default value if unspecified

YosemiteV_Climbing = arcpy.GetParameterAsText(2)
if YosemiteV_Climbing == '#' or not YosemiteV_Climbing:
    YosemiteV_Climbing = "C:\\GIS\\scratch.gdb\\YosemiteV_Climbing" # provide a default value if unspecified

Yose_Climbing_Lines = arcpy.GetParameterAsText(3)
if Yose_Climbing_Lines == '#' or not Yose_Climbing_Lines:
    Yose_Climbing_Lines = "D:\\gis\\GIS_Coursera\\5. Geospatial Analysis Project\\Work\\data\\results.gdb\\Yose_Climbing_Lines" # provide a default value if unspecified

# Local variables:
Reclass_Pos_1 = "C:\\GIS\\scratch.gdb\\Reclass_Pos_1"
Clipped_Streams_PolylineToRa = "C:\\GIS\\scratch.gdb\\Clipped_Streams_PolylineToRa"
Expand_Clipp1 = "C:\\GIS\\scratch.gdb\\Expand_Clipp1"
Reclass_Expa1 = "C:\\GIS\\scratch.gdb\\Reclass_Expa1"

# Set Geoprocessing environments
arcpy.env.scratchWorkspace = "C:\\GIS\\scratch.gdb"
arcpy.env.workspace = "C:\\GIS\\scratch.gdb"

# Process: Reclassify (7)
arcpy.gp.Reclassify_sa(Pos_Climbing_Areas, "VALUE", "0.002473 16.158496 1;16.158496 25.641379 2;25.641379 33.368173 3;33.368173 40.041313 4;40.041313 46.714452 5;46.714452 53.387592 6;53.387592 60.411950 7;60.411950 67.787526 8;67.787526 76.216755 9;76.216755 89.914253 10", Reclass_Pos_1, "DATA")

# Process: Polyline to Raster
arcpy.PolylineToRaster_conversion(Clipped_Streams, "grid_code", Clipped_Streams_PolylineToRa, "MAXIMUM_LENGTH", "NONE", Pos_Climbing_Areas)

# Process: Expand
arcpy.gp.Expand_sa(Clipped_Streams_PolylineToRa, Expand_Clipp1, "4", "1;2;3;4;5;6;7;8;9")

# Process: Reclassify (8)
arcpy.gp.Reclassify_sa(Expand_Clipp1, "Value", "1 1.800000 1;1.800000 2.600000 2;2.600000 3.400000 3;3.400000 4.200000 4;4.200000 5 5;5 5.800000 6;5.800000 6.600000 7;6.600000 7.400000 8;7.400000 8.200000 9;8.200000 9 10", Reclass_Expa1, "DATA")

# Process: Weighted Overlay
arcpy.gp.WeightedOverlay_sa("('C:\\GIS\\scratch.gdb\\Reclass_Pos_1' 60 'Value' (1 Restricted; 2 Restricted; 3 Restricted; 4 Restricted; 5 Restricted; 6 6; 7 7; 8 8; 9 9; 10 10;NODATA NODATA); 'C:\\GIS\\scratch.gdb\\Reclass_Expa1' 40 'Value' (1 1; 2 2; 3 3; 4 4; 5 5; 6 6; 7 7; 8 8; 9 9; 10 10;NODATA NODATA));1 10 1", YosemiteV_Climbing)

# Process: Con
arcpy.gp.Con_sa(YosemiteV_Climbing, YosemiteV_Climbing, Yose_Climbing_Lines, "", "Value > 0")

